### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by paf31**
Not finished yet...

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me so far. Could mention `extract` is the dual to `return`, `<<=` is the dual to `>>=`, and `duplicate` is the dual to `join`? Again maybe that's redundant though, due to being able to see from the types that the arrows are reversed from the `Monad` equivalents.

**Comment by paf31** [comment]
Ok, I think this is good to go. I also removed `foreverA`, since as far as I can tell, it can never work. Alternatively, we could add a `Lazy1` constraint.

@garyb Thoughts?

**Comment by paf31** [comment]
No, come to think of it, I can't think of any useful instances which wouldn't use `tailrec`'s version of `forever` instead.

**Comment by garyb** [comment]
If I was going to be extremely petty - we use both flipped and reversed in describing argument order again, and there's a mixture of descriptions ending with a full stop or not. But it looks great to me, nice work. :cool:

**Comment by paf31** [comment]
No, good points. I'll fix those up then merge, thanks.

**Pull request merged**
