### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by thomashoneyman**
This PR migrates control to use GitHub Actions instead of Travis for CI, as tracked for all core libraries in https://github.com/purescript/purescript/issues/3962. It also updates the installation instructions to refer to [Spago](https://github.com/purescript/spago) instead of Bower.

### CODE REVIEW

**Review by kl0tl — APPROVED** [review]
I inadvertently removed the MonadZero instance for Array in https://github.com/purescript/purescript-control/pull/64 😬 Do you prefer that we add it back and censor user defined warnings here or in another pull request?

**Review by JordanMartinez — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Either or. I've approved this PR, so you can merge this @kl0tl if you want to submit a PR adding the instance back in.

**Comment by hdgarrood** [comment]
We said we would keep the instances in for now, didn’t we?

**Comment by JordanMartinez** [comment]
I've opened #66 to address the MonadZero instance issue.

**Pull request merged**
