### PR TITLE
0.8 updates

### LINKED ISSUE #24: Draw a MonadZero out of MonadPlus?
See also: https://github.com/garyb/purescript-quickcheck-laws/issues/7

I think that the situation is this:
* Suppose we have some type `A :: * -> *` with `Alternative` and `Monad` instances.
* For such a type to have a `MonadPlus` instance, it currently needs to satisfy:
  * Distributivity: `(x <|> y) >>= f == (x >>= f) <|> (y >>= f)`
  * Annihilation: `empty >>= f = empty`
* There is at least one such type `A` for which `guard` is useful but which does not satisfy distributivity; `Maybe`.
* We want all our instances to be law-abiding, but we also want to be able to use functions like `guard` with types like `Maybe`.
* `guard` should include a constraint to ensure that the type satisifies annihilation.

Therefore, I propose that we add a new empty class as follows:

```purescript
class (Monad m, Alternative m) <= MonadZero m
```

with the annihilation law. Then, `MonadPlus` would only have a `MonadZero` constraint, and the distributivity law. Finally, `guard` should have a `MonadZero` constraint.

Then `Maybe` could have `MonadZero` but not `MonadPlus`, and we could use `guard` with it.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #24, resolves #25

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks great, thanks!

**Comment by garyb** [comment]
What's the plan with `MonadZero`? Do we just want to do away with `MonadPlus` and just have `MonadZero` with the annhiliation law?

What law would `MonadOr` have if we did have that and `MonadPlus`? (I assume `MonadPlus` keeps distribution)

**Comment by paf31** [comment]
`MonadZero m <= MonadPlus m` adds the distribution law, right?

```
(x <|> y) >>= f == (x >>= f) <|> (y >>= f)
```

This fails for `Maybe`, as we know, but passes for other things (like `List`)

**Comment by garyb** [comment]
Cool, yeah, that was my understanding:

- `class (Monad m, Alternative m) <= MonadZero m`, w/annihilation `empty >>= f = empty`
- `class MonadZero m <= MonadPlus m`, w/distribution `(x <|> y) >>= f == (x >>= f) <|> (y >>= f)`

But `MonadOr` was kicked around as a potential class too, and I wasn't sure if we want it, and if we do, what's the law(s) for that?

I'll add `MonadZero` & `MonadPlus` anyway, we can always add `MonadOr` later once this change has been made anyway.

**Comment by paf31** [comment]
I think `MonadOr` has "left catch", but I'm not sure. I think we can add that later, potentially.

**Comment by garyb** [comment]
I've added `MonadZero` now, do you want to take a look?

**Comment by safareli** [comment]
@paf31 yes `MonadOr` has "left catch" law (`(return a) <|> b = return a`). is there a plan to add it?

**Pull request merged**
