### PR TITLE
Added filterM

### PR DESCRIPTION
**Pull request by pseudonom**

### CODE REVIEW

**Comment by paf31** [comment]
Looks good. Could you please add a comment?

**Comment by garyb** [comment]
Could this be generalised to `Foldable` or `Traversable` instead of `[]`?

**Comment by garyb** [comment]
Also, semi related #14 is still open...

**Comment by pseudonom** [comment]
> add a comment

Do you mean a commit comment? Or...

> generalised to `Foldable` or `Traversable` instead of `[]`

It's not obvious to me how one would do that. `filter` itself is currently only defined for `[]`. It could be generalized to `filter :: MonadPlus m => (a -> Bool) -> m a -> m a`, but I don't think that helps for `filterM`. With that filter you'd need to have the ability to swap `(Monad m, Monad n) => m (n a) -> n (m a)`.

**Comment by paf31** [comment]
I think we need a `Refoldable` class :)

Yes, I was just asking for some documentation. We're going to go back and add things retrospectively, but going forwards, I'm going to ask for documentation comments on all new PRs.

**Comment by pseudonom** [comment]
Do participants automatically get notified upon a new commit?

**Comment by paf31** [comment]
No, but I check my pull requests list on a fairly frequent basis. Your best bet is to just ping me with a @-mention.

**Comment by paf31** [comment]
Looks good to me. @garyb ?

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
Oops, could you please bring this up to date with master, and rebase, @pseudonom ?

**Comment by pseudonom** [comment]
Rebased

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
